import React, { useEffect, useState, useCallback } from 'react';
import { CreditCard, Plus, Receipt } from 'lucide-react';
import Badge from '../../components/ui/Badge';
import Select from '../../components/ui/Select';
import Input from '../../components/ui/Input';
import Button from '../../components/ui/Button';
import Modal from '../../components/ui/Modal';
import { Table, Thead, Th, Tbody, Tr, Td } from '../../components/ui/Table';
import EmptyState from '../../components/ui/EmptyState';
import { PageLoader } from '../../components/ui/Loader';
import { formatCurrency, formatDateTime } from '../../utils/formatters';
import { toast } from '../../store/useToastStore';
import { superadminService } from '../../services/superadmin.service';

const STATUS_OPTS = [
  { value: '', label: 'All Statuses' },
  { value: 'SUCCESS', label: 'Success' },
  { value: 'PENDING', label: 'Pending' },
  { value: 'FAILED', label: 'Failed' },
];

const PLAN_OPTS = [
  { value: '', label: 'All Plans' },
  { value: 'YEARLY', label: 'Yearly Plan' },
  { value: 'CUSTOM', label: 'Custom Plan' },
];

const EMPTY_PAYMENT_FORM = {
  schoolId: '',
  amount: '',
  plan: 'YEARLY',
  referenceId: '',
  notes: '',
  paymentDate: new Date().toISOString().slice(0, 10), // Default to today
};

export default function PaymentsPage() {
  const [payments, setPayments] = useState([]);
  const [schools, setSchools] = useState([]); // For the add payment dropdown
  const [meta, setMeta] = useState({});
  const [loading, setLoading] = useState(true);
  
  const [status, setStatus] = useState('');
  const [plan, setPlan] = useState('');
  const [page, setPage] = useState(1);

  const [createOpen, setCreateOpen] = useState(false);
  const [form, setForm] = useState(EMPTY_PAYMENT_FORM);
  const [saving, setSaving] = useState(false);

  const loadPayments = useCallback(async (p = page, s = status, pl = plan) => {
    setLoading(true);
    try {
      const res = await superadminService.listPayments({ page: p, status: s, plan: pl });
      setPayments(res.data);
      setMeta(res.meta);
    } catch {
      toast.error('Failed to load payments');
    } finally {
      setLoading(false);
    }
  }, []);

  const loadSchools = async () => {
    try {
      // Just loading a robust amount for the dropdown
      const res = await superadminService.listSchools({ limit: 1000 });
      setSchools(res.data);
    } catch (err) {
      toast.error('Failed to fetch schools for dropdown');
    }
  };

  useEffect(() => {
    loadPayments(page, status, plan);
  }, [page, status, plan, loadPayments]);

  const handleCreate = async () => {
    if (!form.schoolId || !form.amount || !form.plan) {
      return toast.error('Please fill all required fields');
    }

    setSaving(true);
    try {
      await superadminService.createPayment({
        ...form,
        amount: Number(form.amount)
      });
      toast.success('Payment logged successfully');
      setCreateOpen(false);
      setForm(EMPTY_PAYMENT_FORM);
      loadPayments(1, status, plan);
    } catch (err) {
      toast.error(err.message || 'Failed to log payment');
    } finally {
      setSaving(false);
    }
  };

  const openCreateModal = () => {
    setForm(EMPTY_PAYMENT_FORM);
    loadSchools();
    setCreateOpen(true);
  };

  const field = (k) => (e) => setForm((f) => ({ ...f, [k]: e.target.value }));

  // Options for modal dropdown
  const schoolOptions = [
    { value: '', label: 'Select a School...' },
    ...schools.map(s => ({ value: s._id, label: `${s.name} (${s.schoolId})` }))
  ];
  
  const planOptionsForForm = [
    { value: 'YEARLY', label: 'Yearly Plan' },
    { value: 'CUSTOM', label: 'Custom / Specific' }
  ];

  return (
    <div className="space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center gap-3">
        <div className="flex-1">
          <h1 className="text-xl font-bold text-gray-900">Subscription Tracking</h1>
          <p className="text-sm text-gray-500 mt-0.5">Track payments generated by schools using this platform</p>
        </div>
        <Button size="sm" onClick={openCreateModal}>
          <Plus size={15} /> Log Payment
        </Button>
      </div>

      {/* Filters */}
      <div className="flex items-center gap-3 flex-wrap">
        <Select options={STATUS_OPTS} value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="w-36" />
        <Select options={PLAN_OPTS} value={plan} onChange={(e) => { setPlan(e.target.value); setPage(1); }} className="w-40" />
      </div>

      {loading ? (
        <div className="flex justify-center py-20"><PageLoader /></div>
      ) : payments.length === 0 ? (
        <EmptyState
          icon={Receipt}
          title="No subscription payments yet"
          description="Log custom or yearly subscription payments from schools here."
          action={
            <Button size="sm" onClick={openCreateModal}>
              <Plus size={15} /> Log Payment
            </Button>
          }
        />
      ) : (
        <>
          <Table>
            <Thead>
              <Th>School</Th>
              <Th>School ID</Th>
              <Th>Plan</Th>
              <Th>Amount</Th>
              <Th>Reference</Th>
              <Th>Status</Th>
              <Th>Date</Th>
            </Thead>
            <Tbody>
              {payments.map((p) => (
                <Tr key={p._id}>
                  <Td>
                    <div className="font-medium text-gray-900">{p.schoolId?.name || '—'}</div>
                    <div className="text-xs text-gray-500">{p.schoolId?.email}</div>
                  </Td>
                  <Td className="font-mono text-sm text-gray-500">{p.schoolId?.schoolId || '—'}</Td>
                  <Td>
                    <span className="font-medium text-xs text-violet-700 bg-violet-50 px-2 py-1 rounded">
                      {p.plan}
                    </span>
                  </Td>
                  <Td className="font-semibold">{formatCurrency(p.amount)}</Td>
                  <Td className="text-sm text-gray-500">{p.referenceId || '—'}</Td>
                  <Td><Badge label={p.status} variant={p.status} /></Td>
                  <Td className="text-gray-400">{formatDateTime(p.paymentDate || p.createdAt)}</Td>
                </Tr>
              ))}
            </Tbody>
          </Table>

          {/* Pagination */}
          {meta?.pages > 1 && (
            <div className="flex items-center justify-end gap-2 pt-2">
              <Button
                variant="secondary" size="sm"
                disabled={page <= 1}
                onClick={() => setPage(page - 1)}
              >
                Previous
              </Button>
              <span className="text-sm text-gray-500">Page {page} of {meta.pages}</span>
              <Button
                variant="secondary" size="sm"
                disabled={page >= meta.pages}
                onClick={() => setPage(page + 1)}
              >
                Next
              </Button>
            </div>
          )}
        </>
      )}

      {/* Manual Add Payment Modal */}
      <Modal
        open={createOpen}
        onClose={() => setCreateOpen(false)}
        title="Log Subscription Payment"
        footer={
          <>
            <Button variant="secondary" onClick={() => setCreateOpen(false)}>Cancel</Button>
            <Button loading={saving} onClick={handleCreate}>Save Payment</Button>
          </>
        }
      >
        <div className="space-y-4">
          <Select
            label="School"
            options={schoolOptions}
            value={form.schoolId}
            onChange={field('schoolId')}
            required
          />
          <div className="grid grid-cols-2 gap-3">
            <Select
              label="Plan"
              options={planOptionsForForm}
              value={form.plan}
              onChange={field('plan')}
              required
            />
            <Input
              label="Amount (INR)"
              type="number"
              value={form.amount}
              onChange={field('amount')}
              placeholder="e.g. 5000"
              required
            />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <Input
              label="Transaction Date"
              type="date"
              value={form.paymentDate}
              onChange={field('paymentDate')}
              required
            />
            <Input
              label="Reference ID / Check No. (Optional)"
              value={form.referenceId}
              onChange={field('referenceId')}
              placeholder="e.g. UPI123456"
            />
          </div>
          <Input
            label="Notes (Optional)"
            value={form.notes}
            onChange={field('notes')}
            placeholder="Add any internal notes..."
          />
        </div>
      </Modal>

    </div>
  );
}
